# Generated by Django 3.1.7 on 2021-05-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_vehicleserve_labour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleserve',
            name='labour',
            field=models.IntegerField(),
        ),
    ]
