# Generated by Django 3.1.7 on 2021-05-10 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_flat_side'),
        ('services', '0003_auto_20210510_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleserve',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distrct_set', to='buildings.district'),
        ),
    ]
