# Generated by Django 3.1.7 on 2021-05-10 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_flat_side'),
        ('services', '0005_auto_20210510_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleserve',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_set', to='buildings.district'),
        ),
    ]
