# Generated by Django 3.1.7 on 2021-05-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210510_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleserve',
            name='destination',
        ),
    ]
