# Generated by Django 3.1.7 on 2021-05-10 04:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210510_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Owner', 'Owner'), ('Tenent', 'Tenent'), ('Servant', 'Servant')], max_length=100, null=True),
        ),
    ]
