# Generated by Django 3.1.4 on 2020-12-27 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=17)),
                ('total_stairs', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('lift', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('size', models.FloatField()),
                ('rent_type', models.CharField(choices=[('Family', 'Family'), ('Bachelor', 'Bachelor')], max_length=50)),
                ('rent', models.IntegerField()),
                ('details', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(upload_to='Buildings/images')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts_set', to='buildings.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlatImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Buildings/images')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='buildings.flat')),
            ],
        ),
    ]
