# Generated by Django 3.1.7 on 2021-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='side',
            field=models.CharField(default='', max_length=100),
        ),
    ]
